name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Start server
        run: npm start

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run lint
